name: Create Production Deployment

on:
  workflow_run:
    workflows: "Create Release"
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID_AWS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_AWS }}

    steps:
      - name: Determine S3 Bucket
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            echo "S3_BUCKET=${{ secrets.S3_BUCKET_STAGING }}" >> $GITHUB_ENV
          else
            echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> $GITHUB_ENV
          fi
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: Update version in index.html
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          sed -i "s/VERSION/$LATEST_TAG/g" ./dist/index.html

      # https://github.com/marketplace/actions/s3-deploy
      - name: Deploy 
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ env.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          delete-removed: true
          no-cache: true
          private: false
          files-to-include: '{.*/**,**}'
