name: Pull Request Title Verification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@v1.0.0
        with:
          regex: '^\[CU-\w{9}\] .+$'
          allow_edit_contributors: false
          fail_on_invalid: true
          token: ${{ secrets.GITHUB_TOKEN }}
