name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
          uses: actions/create-release@v1
    
      - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

      - name: Install dependencies
          run: npm install

      - name: Build project
          run: npm run build
      
      - name: Create Release Tag
          id: create_tag
          uses: christian-draeger/increment-semantic-version@1.1.0
          with:
              current-version: '1.0.0'
              version-fragment: 'bug'

      - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.create_tag.outputs.next-version }}
            release_name: Release ${{ steps.create_tag.outputs.next-version }}
            draft: false
            prerelease: false

      - name: Changelog
          uses: scottbrenner/generate-changelog-action@master
          id: Changelog
          env:
            REPO: ${{ github.repository }}
    